import BarChart from "@/componenets/BarChart"
import RecentOrders from "@/componenets/RecentOrders"
import TopCards from "@/componenets/TopCards"
import Head from "next/head"
import Image from "next/image"
import Header from "../componenets/Header"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100 min-h-screen">
        <Header />
        <TopCards />
        <div className="p-4 grid md:grid-cols-3 grid-cols-1 gap-4">
          <BarChart />
          <RecentOrders />
        </div>
      </main>
    </>
  )
}
